Add hotfix delete and refactored hotfix
prostoLavr/async_lyceum_api pull request #5
Opened 2023-04-30 05:38 UTC by romakot321

2023-04-30 06:01 UTC, prostoLavr requested changes

2023-04-30 06:01 UTC, prostoLavr commented on time_api/api/lessons.py
Replace global const to enum. authenticate.monitor() raises exception when access level is lower then monitor, but next you use it for authenticate teachers.

2023-04-30 06:01 UTC, prostoLavr commented on time_api/api/lessons.py
Teachers can remove lessons, but you use the monitor level.

2023-04-30 06:01 UTC, prostoLavr commented on time_api/migrations/versions/3256e9b567f5_lesson_hotfix.py
Create new migration for a table schema that already is on server.

2023-04-30 06:01 UTC, prostoLavr commented on time_api/schemas/lessons.py
Use sometype | None instead Optional[sometype]

2023-04-30 06:01 UTC, prostoLavr commented on time_api/schemas/lessons.py
Don't use optional lesson_id in answer schema. Vue.JS will raise exception if ID is null.

2023-04-30 06:01 UTC, prostoLavr commented on time_api/services/lessons_hotfix.py
Catch Exception on commit creating and deleting lessons. 45-47 stings are not readable. 56 string is so long, use partial execution.

2023-05-01 05:16 UTC, romakot321 commented on time_api/api/lessons.py
Please, be more attentive. Before checking the access_level there is verification for the cancel of the lessons for the whole day. It was done to ensure that only teachers could cancel the lessons for the whole day, and the monitor(class representative) could cancel only a few lessons.

2023-05-01 05:16 UTC, romakot321 commented on time_api/api/lessons.py
Monitor can create hotfix/remove lessons.

2023-05-01 05:53 UTC, romakot321 reviewed
The required changes were made in the following commits

2023-05-02 10:37 UTC, prostoLavr requested changes

2023-05-02 10:37 UTC, prostoLavr commented on time_api/api/lessons.py
Rename monitor to class_representive. Add to hotifx params required school_id when lesson_id is None. Think about access level.

2023-05-02 10:37 UTC, prostoLavr commented on time_api/schemas/lessons.py
Use it, please

2023-05-02 10:37 UTC, prostoLavr commented on time_api/services/auth.py
Rename monitor to class_representative

2023-05-02 10:37 UTC, prostoLavr commented on time_api/services/auth.py
Remove test data from production build

2023-05-02 10:37 UTC, prostoLavr commented on time_api/services/lessons.py
Replace sigle condition on 77 line to lesson cycle with condition everything.

2023-05-02 10:37 UTC, prostoLavr commented on time_api/services/lessons.py
Replace enumarate to range

2023-05-02 10:37 UTC, prostoLavr commented on time_api/services/lessons.py
To start new line in condition use:
`(some == some and \n some == some)`

2023-05-05 04:02 UTC, merged